# Generated by Django 5.2 on 2025-04-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
